ARXIVNG-3517 final front end edits to tabs
arXiv/arxiv-browse pull request #187
Opened 2020-09-08 18:52 UTC by SBBCornell

This branch includes visual changes to the labs in tabs on both mobile and desktop. There are other tickets related to some functionality and placement of the tabs, but this branch is focused only on the visual display of the tabs themselves.

Desktop (conservative colors to not rock the boat):
![Screen Shot 2020-09-08 at 2 48 31 PM](https://user-images.githubusercontent.com/56078140/92515932-65bcdb00-f1e2-11ea-97d3-6c549ff6e588.png)

Mobile (bolder use of color, in keeping with stats and other new pages):
![Screen Shot 2020-09-08 at 2 49 42 PM](https://user-images.githubusercontent.com/56078140/92516021-8edd6b80-f1e2-11ea-9177-99c1cd4834c2.png)

2020-09-09 14:35 UTC, mhl10 requested changes
This is looking great! I noticed a bug toggling the CORE Recommender so I'll select "request changes" here to remind myself to fix it.

2020-09-09 17:53 UTC, ep538 approved these changes
Looks good!!

2020-09-09 19:41 UTC, bmaltzan approved these changes
Looks great!

2020-09-10 18:40 UTC, mhl10 approved these changes

2020-09-28 18:20 UTC, merged