ARXIVNG-5256: institutional-banner
arXiv/arxiv-browse pull request #297
Opened 2022-11-10 15:35 UTC by bmaltzan

Create endpoint for looking up member institutions by ip address.
If found, cache for 30 days or until browser closes.
If not previously cached, and db is down, user won't see member acknowledgement until db is restored, but abs page will work if .abs file can be read from nfs.
Bots probably won't execute js, so may reduce number of queries.

2022-11-10 18:03 UTC, SBBCornell approved these changes
The description of the solution sounds good to me. I wont attempt to review the code, however.

2022-11-15 22:42 UTC, bdc34 requested changes

2022-11-15 22:42 UTC, bdc34 commented on browse/templates/base.html
> +    function setCookie(cname, cvalue, exdays) {
Can you do this with [local storage ](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) instead of a cookie?

2022-11-15 22:45 UTC, bdc34 commented on browse/templates/base.html
> +    function setCookie(cname, cvalue, exdays) {
Also, can you move this to base so that all our projects can use this?

2022-11-30 17:52 UTC, bdc34 approved these changes

2022-11-30 19:16 UTC, merged