Arxivce 805 html route
arXiv/arxiv-browse pull request #441
Opened 2023-12-12 21:00 UTC by mnazzaro

This branch includes the latest HTML conversion styles as well as the capability to serve classic html papers and conversions from browse in GCP. It also updates the sync script to handle html submissions and has some minor changes to the abstract page.

2023-12-12 21:16 UTC, bdc34 requested changes
There were some changes unrelated to html-papers in the extra_services.html. If these are not part of the HTML papers work, please don't include them.

2023-12-12 21:16 UTC, bdc34 commented on browse/templates/abs/extra_services.html
> +  <li><a href="{{url_for('src.src', arxiv_id=requested_id)}}" class="abs-button download-eprint">TeX Source</a></li>
Do not change to src unless there is a Jira ticket that explicitly requests this.

2023-12-12 21:16 UTC, bdc34 commented on browse/templates/abs/extra_services.html
> -      {%- elif format == 'other' -%}
This removal is not in master or develop. I'm not sure why adding the HTML should remove the "Other Formats" button.

2023-12-12 21:16 UTC, bdc34 commented on browse/templates/abs/extra_services.html
> +          {%- if 'other' in formats -%}
This code is not in master or develop and doesn't seem to have anything to do with HTML-papers.

2023-12-12 21:47 UTC, bdc34 commented
Looks good.

2023-12-12 21:47 UTC, bdc34 approved these changes

2023-12-13 17:24 UTC, SBBCornell commented on browse/static/css/latexml_styles.css
> +    }
```suggestion
    }
    .ltx_page_main > .ltx_TOC {
        padding-top: 10vh;
    }
```

2024-03-29 17:32 UTC, bdc34 commented
I suspect this PR can be closed due to this code being merged from other places. These features are live on the site.

2024-03-29 17:33 UTC, bdc34 commented
Mark says these are already live and this can be closed.

2024-03-29 17:33 UTC, closed without merging